<?php

use Illuminate\Support\Facades\Route;

/**
 * Beha Backend — Web routes (minimal; this is a headless API).
 *
 * The React SPA at /home/z/my-project/beha/frontend is the primary UI.
 * This file only serves:
 *   - /            → API welcome page
 *   - /up          → Laravel health check
 *   - Filament admin routes (auto-registered by Filament v4)
 *
 * All business endpoints live in routes/api.php (Sanctum-protected).
 */

Route::get('/', fn () => view('welcome'))->name('home');

// Filament admin panel is registered by app/Providers/Filament/AdminPanelProvider
// (auto-generated by `php artisan filament:install` on first run).
